### ISSUE TITLE
便携版如何更新，更新时能否自定义保存路径，便携版的判定条件是什么？

### ISSUE THREAD

**Issue by AdoShan** [Jrohy/cfw-updater#1]
我使用的是zip的解压出来直接用，使用软件检测到了CFW版本，使用工具更新之后竟然重新安装了一个CFW而且也实在当前用户的AppData\Local\Programs目录下安装了新版本的CFW

**Comment by Jrohy** [comment]
如果是安装版的安装目录下面会有Uninstall Clash for Windows.exe用来卸载安装版的, 如果不存在这个文件就判断为便携版

**Comment by Jrohy** [comment]
正常情况都是根据当前cfw进程的运行所在目录来自动更新对应目录的程序的， 是不是运行了安装版来执行更新检查下

**Comment by Jrohy** [comment]
系统测试只测试了win11和win10, win7的就没测过(没环境测)。 顺便提下官方没有zip版，便携版只有7z格式的

**Comment by rebron1900** [comment]
他这个问题就是我当时出现的问题。现在应该修复了 #4
