### ISSUE TITLE
国内下载有点慢

### ISSUE THREAD

**Issue by SummerSec** [Jrohy/cfw-updater#2]
建议使用 https://ghproxy.com/ 下载

**Comment by Jrohy** [comment]
@SummerSec 这种随时可能没法用的(而且都能翻了就不建议占用别人用爱发电的公益资源)。如果下载慢就切换下配置，下载快慢由cfw配置的节点速度来决定的
![image](https://user-images.githubusercontent.com/12463263/150757149-296931b8-e9a7-4284-bda6-a991f21f81fb.png)
