### ISSUE TITLE
便捷版更新问题

### ISSUE THREAD

**Issue by realcirno** [Jrohy/cfw-updater#3]
便捷版更新的时候能否保留Data文件夹，更新之后全被删了XD

**Comment by Jrohy** [comment]
什么系统呢

**Comment by realcirno** [comment]
> 什么系统呢

Win10  64位

**Comment by Jrohy** [comment]
有保留的，我自己使用的就是便携版+data的方式，win10和win11都测试使用过

**Comment by Jrohy** [comment]
你的数据目录名称是Data而不是data么

**Comment by realcirno** [comment]
> 你的数据目录名称是Data而不是data么
是的，XD，我改一下吧

**Comment by lqzhgood** [comment]
。。。。 我的也被删了 名称是 data
太蛋疼了
OS  Windows11
