### ISSUE TITLE
TUN模式下不能正常更新

### ISSUE THREAD

**Issue by rebron1900** [Jrohy/cfw-updater#4]
RT，之前用过几次，开了TUN和服务模式后能下载能汉化，但是在替换的时候出问题了，似乎是服务模式运行了后台程序没有强制结束导致的这个问题
我昨天把TUN和服务模式关了之后再使用可以完美重启。

如果不是因为TUN和服务模式，那是我那里没操作对呢？

**Comment by Jrohy** [comment]
唉我没试过用tun模式，回去测试下

**Comment by Jrohy** [comment]
难得有bug可以更新下，还以为项目快到归档模式了😂

**Comment by rebron1900** [comment]
之前以为是我电脑的问题，后来就弃用了，但是每次又要手动汉化觉得很麻烦就又拿出来用，做了一下测试，得到了以上结论。
具体是不是这个原因大佬可以测试一下。

**Comment by rebron1900** [comment]
另外现在必须启动cfw才可以更新，可不可以输入主程序或者选择或者搜索得方式？我之前想手动完全关闭程序更新，但是和你设置得默认条件冲突了。

**Comment by Jrohy** [comment]
不行的，必须启动后才能更新，因为网络下载和更新的程序位置都要依赖已运行的cfw

**Comment by Jrohy** [comment]
必须得有个cfw进程才能判断出是不是绿色版，假如绿色版是程序是位于哪里，github的网络资源下载也必须依赖于走cfw代理才能下载下来。包括安装版的也有全局安装还有用户级别安装，都是得运行才知道要更新到什么位置(包括汉化资源)

**Comment by Jrohy** [comment]
确实有问题，有另外的进程没关闭导致无法更新。后面会优化下

**Comment by rebron1900** [comment]
> 确实有问题，有另外的进程没关闭导致无法更新。后面会优化下

谢谢，期待更新。

**Comment by Jrohy** [comment]
是不是用的绿色版+ 便携模式才这样

**Comment by rebron1900** [comment]
> 是不是用的绿色版+ 便携模式才这样

目前时这种配置运行的。

**Comment by Jrohy** [comment]
已发布新版，重新运行updater即可自动更新到最新，可以测试下效果

**Comment by Jrohy** [comment]
已发布新版，重新运行updater即可自动更新到最新，可以测试下效果
