### ISSUE TITLE
似乎出bug了，一直卡在更新中

### ISSUE THREAD

**Issue by Silentely** [Jrohy/cfw-updater#5]
已经卡在这个界面十来分钟了
![3bce7e878ccb70acbc5b774b7931ed93.png](https://img.mjj.today/2022/09/07/3bce7e878ccb70acbc5b774b7931ed93.png)

**Comment by Jrohy** [comment]
cfw有开启什么特殊模式么，太久就退出来。cfw-updater 同级目录下应该有已经弄好的更新包，只是可能因为程序占用或者其他原因无法更新到指定目录

**Comment by Silentely** [comment]
> cfw有开启什么特殊模式么，太久就退出来。cfw-updater 同级目录下应该有已经弄好的更新包，只是可能因为程序占用或者其他原因无法更新到指定目录

我尝试移出目录再更新似乎可以正常更新了 暂无报错，但是这个BoyceLig版本汉化包提示不存在，实际大佬是有更新https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.19.29

正在获取BoyceLig/Clash_Chinese_Patch的0.19.29版本汉化包...
BoyceLig/Clash_Chinese_Patch的0.19.29汉化补丁不存在, 正在切换到另一种汉化补丁

**Comment by Jrohy** [comment]
@Silentely 谢谢反馈，目前还不支持zip格式的翻译包，后面可能会适配下

**Comment by Jrohy** [comment]
@Silentely 1.10.5已支持zip格式的翻译包，重新运行下updater就能自动更新了

**Comment by Silentely** [comment]
1.10.5 似乎还存在bug 0.20.4版汉化是存在（https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.20.4）  ，但是软件更新依旧提示不存在
![4c494a416ad67c7c6bd5055ab2de2cbb.jpg](https://img.mjj.today/2022/09/23/4c494a416ad67c7c6bd5055ab2de2cbb.jpg)

**Comment by Jrohy** [comment]
@Silentely 确实有问题，我修复下

**Comment by Jrohy** [comment]
github的页面规则改了，导致获取不到翻译包是什么名字格式的，我看看怎么适配下

**Comment by Jrohy** [comment]
@Silentely 已发布新版修复，重新运行更新下

**Comment by Silentely** [comment]
> @Silentely 已发布新版修复，重新运行更新下

谢大佬
