### ISSUE TITLE
更新过程希望加入选择第三方内核功能

### ISSUE THREAD

**Issue by poyih** [Jrohy/cfw-updater#6]
https://github.com/MetaCubeX/Clash.Meta/releases
该内核支持多种原版内核不兼容的协议，每次cfw更新后都需要手动替换内核。

**Comment by Jrohy** [comment]
这个工具只是更新cfw软件本身而已，不会去管clash内核的

**Comment by poyih** [comment]
好吧，其实它替换内核的方法跟汉化差不多，就是替换个文件。
