### ISSUE TITLE
如果将 cfw-updater 放到 cfw 目录中运行，会有bug

### ISSUE THREAD

**Issue by lqzhgood** [Jrohy/cfw-updater#7]
会有这两个问题
https://github.com/Jrohy/cfw-updater/issues/3
https://github.com/Jrohy/cfw-updater/issues/5

应该是程序会清空cfw目录，然后 cfw-update 又在目录中运行的缘故，而且会删除目录中的 `data`

**Comment by Jrohy** [comment]
不要放在cfw目录里在里面执行，可以建个单独的目录单独放在里面来运行

**Comment by Jrohy** [comment]
确实有这个问题，我看看怎么规避

**Comment by lqzhgood** [comment]
我觉得默认把 update 放到 cfw 目录更合理，这样也不用判断 cfw 的运行目录了， 就当 cfw 自带的 update 来使用。
cfw 和 update 就可以一起打包作为便携版使用

**Comment by Jrohy** [comment]
我有空测试下，放在一起更新cfw的时候不删除旧版，直接整个替换看看行不行。 放在一起确实也合理

**Comment by Jrohy** [comment]
1.10.7版本已修复，重新运行来更新下
